// Editá las consignas directamente en este archivo desde GitHub.
// Formato de cada entrada: ['emoji de categoría', 'consigna', 'autor']
// Conservá las comas, comillas y corchetes para que la aplicación siga funcionando.
const seeds = [
  ['✈️','TOP-3 lugares del mundo a los que volverías a ir','top3master'],
  ['✈️','TOP-3 lugares del mundo que te gustaría visitar que aún no visitaste','narian'],
  ['🎮','TOP-3 videojuegos que jugas cuando tenes un rato','asdf'],
  ['🎮','TOP-3 videojuegos que te emocionan','sebas'],
  ['🎮','TOP-3 libros que recomendas','weby'],
  ['⚽','TOP-3 Deportes que menos te gustan','tope'],
  ['⚽','TOP-3 Deportes para ver','majo'],
  ['⚽','TOP-3 Deportes para hacer','top3master'],
  ['🤔','TOP-3 señales que una persona te va a caer bien','narian'],
  ['🤔','TOP-3 señales que una persona te va a caer mal (prejuicios)','asdf'],
  ['🤔','TOP-3 excusas para cancelar un plan','sebas'],
  ['🤔','TOP-3 planes perfectos para una primera cita','weby'],
  ['😂','TOP-3 proceres de tu país','sebas'],
  ['😂','TOP-3 de buzzwords (palabras que se usan en corpos)','sebas'],
  ['😂','TOP-3 hechos históricos de tu país','sebas'],
  ['😂','TOP-3 insectos','sebas'],
  ['🎬','TOP-3 películas para un roadtrip','weby'],
  ['🎬','TOP-3 peliculas de acción','tope'],
  ['🎬','TOP-3 peliculas de terror','majo'],
  ['🎬','TOP-3 peliculas enfermas','top3master'],
  ['🎬','TOP-3 peliculas de drama','narian'],
  ['🎬','TOP-3 peliculas relacionadas con música (no musicales)','asdf'],
  ['🎬','TOP-3 heroes de acción','sebas'],
  ['🎬','TOP-3 villanos del cine','weby'],
  ['🎬','TOP-3 sitcoms','tope'],
  ['🎵','TOP-3 bandas que te gustaría ver en vivo que aún no viste','majo'],
  ['🎵','TOP-3 canciones para cantar','top3master'],
  ['🎵','TOP-3 canciones para un día de lluvia','narian'],
  ['🎵','TOP-3 canciones para la mañana del Domingo','asdf'],
  ['🎵','TOP-3 canciones para escuchar a todo volumen en el auto','sebas'],
  ['🍕','TOP-3 comidas que elegirías para tu última cena','weby'],
  ['🍕','TOP-3 combinaciones de pizza','tope'],
  ['🍕','TOP-3 de empanadas','majo'],
  ['🍕','TOP-3 de facturas','top3master'],
  ['🍕','TOP-3 de formas de comer papa','narian'],
  ['🍕','TOP-3 de formas de comer queso','asdf'],
  ['🍕','TOP-3 de ingredientes de picada','sebas'],
  ['😂','TOP-3 superpoderes','top3master'],
  ['😂','TOP-3 herramientas','top3master'],
  ['🎬','TOP-3 comediantes de stand-up','top3master'],
  ['⚽','TOP-3 deportistas de tu país','top3master'],
];
